# Generated by Django 5.1.6 on 2025-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="mobile_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
