# Generated by Django 5.1 on 2024-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Precaution', '0004_disease_video_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='video',
            field=models.FileField(upload_to='media/Registration/'),
        ),
    ]
