# Generated by Django 4.1 on 2025-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorFind", "0002_remove_doctor_disease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("Ayurveda", "Ayurveda"),
                    ("Herbal Medicine", "Herbal Medicine"),
                    ("Naturopathy", "Naturopathy"),
                    ("Homeopathy", "Homeopathy"),
                    ("Cardiology", "Cardiology"),
                    ("Dermatology", "Dermatology"),
                    ("Neurology", "Neurology"),
                    ("Pediatrics", "Pediatrics"),
                    ("Psychiatry", "Psychiatry"),
                    ("Radiology", "Radiology"),
                    ("Surgery", "Surgery"),
                    ("Orthopedics", "Orthopedics"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Oncology", "Oncology"),
                ],
                max_length=50,
            ),
        ),
    ]
