# Generated by Django 4.1 on 2025-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorFind", "0005_alter_doctor_speciality_delete_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("Ayurveda - General", "Ayurveda - General"),
                    ("Panchakarma Therapy", "Panchakarma Therapy"),
                    ("Marma Therapy", "Marma Therapy"),
                    ("Kshar Sutra Therapy", "Kshar Sutra Therapy"),
                    ("Leech Therapy", "Leech Therapy"),
                    ("Herbal Medicine", "Herbal Medicine"),
                    ("Naturopathy", "Naturopathy"),
                    ("Homeopathy", "Homeopathy"),
                    ("Andrology (Men’s Health)", "Andrology (Men’s Health)"),
                    ("Ayurvedic Urology", "Ayurvedic Urology"),
                    ("Gynecology & Obstetrics", "Gynecology & Obstetrics"),
                    ("PCOS & Hormonal Disorders", "PCOS & Hormonal Disorders"),
                    ("Pregnancy & Postpartum Care", "Pregnancy & Postpartum Care"),
                    ("Cardiology", "Cardiology"),
                    ("Dermatology", "Dermatology"),
                    ("Neurology", "Neurology"),
                    ("Pediatrics", "Pediatrics"),
                    ("Psychiatry", "Psychiatry"),
                    ("Radiology", "Radiology"),
                    ("Surgery", "Surgery"),
                    ("Orthopedics", "Orthopedics"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Oncology", "Oncology"),
                    ("Chiropractic Medicine", "Chiropractic Medicine"),
                    ("Physiotherapy", "Physiotherapy"),
                    ("Acupuncture", "Acupuncture"),
                    ("Unani Medicine", "Unani Medicine"),
                    ("Siddha Medicine", "Siddha Medicine"),
                    ("Yoga Therapy", "Yoga Therapy"),
                ],
                max_length=50,
            ),
        ),
    ]
