# Generated by Django 5.1.6 on 2025-03-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorFind", "0006_alter_doctor_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.CharField(max_length=100),
        ),
    ]
