# Generated by Django 5.1.6 on 2025-03-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorFind", "0007_alter_doctor_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_images/"),
        ),
    ]
